version: '3.7'

services:
  contacts-api:
    container_name: pro-contacts-api
    image: pro-contacts-api
    build:
      context: ./backend
    environment:
      DATABASE_URL: "host=contacts-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - contacts-db
  contacts-db:
    container_name: pro-contacts-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  contacts-frontend:
    container_name: pro-contacts-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
volumes:
  pgdata: {}