version: '3.7'

services:
  contacts-api:
    container_name: api-container
    image: pro-contacts-api
    build: .
    environment:
      DATABASE_URL: "host=contacts-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - contacts-db
  contacts-db:
    container_name: db-container
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}